// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package shared

type UnionString string

func (UnionString) ImplementsAccountCustomFieldsUnion()                         {}
func (UnionString) ImplementsAccountNewParamsCustomFieldsUnion()                {}
func (UnionString) ImplementsAccountUpdateParamsCustomFieldsUnion()             {}
func (UnionString) ImplementsAccountPlanCustomFieldsUnion()                     {}
func (UnionString) ImplementsAccountPlanNewParamsCustomFieldsUnion()            {}
func (UnionString) ImplementsAccountPlanUpdateParamsCustomFieldsUnion()         {}
func (UnionString) ImplementsAggregationCustomFieldsUnion()                     {}
func (UnionString) ImplementsAggregationNewParamsCustomFieldsUnion()            {}
func (UnionString) ImplementsAggregationUpdateParamsCustomFieldsUnion()         {}
func (UnionString) ImplementsCompoundAggregationCustomFieldsUnion()             {}
func (UnionString) ImplementsCompoundAggregationNewParamsCustomFieldsUnion()    {}
func (UnionString) ImplementsCompoundAggregationUpdateParamsCustomFieldsUnion() {}
func (UnionString) ImplementsContractCustomFieldsUnion()                        {}
func (UnionString) ImplementsContractNewParamsCustomFieldsUnion()               {}
func (UnionString) ImplementsContractUpdateParamsCustomFieldsUnion()            {}
func (UnionString) ImplementsCustomFieldsAccountUnion()                         {}
func (UnionString) ImplementsCustomFieldsAccountPlanUnion()                     {}
func (UnionString) ImplementsCustomFieldsAggregationUnion()                     {}
func (UnionString) ImplementsCustomFieldsCompoundAggregationUnion()             {}
func (UnionString) ImplementsCustomFieldsMeterUnion()                           {}
func (UnionString) ImplementsCustomFieldsOrganizationUnion()                    {}
func (UnionString) ImplementsCustomFieldsPlanUnion()                            {}
func (UnionString) ImplementsCustomFieldsPlanTemplateUnion()                    {}
func (UnionString) ImplementsCustomFieldsProductUnion()                         {}
func (UnionString) ImplementsCustomFieldUpdateParamsAccountUnion()              {}
func (UnionString) ImplementsCustomFieldUpdateParamsAccountPlanUnion()          {}
func (UnionString) ImplementsCustomFieldUpdateParamsAggregationUnion()          {}
func (UnionString) ImplementsCustomFieldUpdateParamsCompoundAggregationUnion()  {}
func (UnionString) ImplementsCustomFieldUpdateParamsMeterUnion()                {}
func (UnionString) ImplementsCustomFieldUpdateParamsOrganizationUnion()         {}
func (UnionString) ImplementsCustomFieldUpdateParamsPlanUnion()                 {}
func (UnionString) ImplementsCustomFieldUpdateParamsPlanTemplateUnion()         {}
func (UnionString) ImplementsCustomFieldUpdateParamsProductUnion()              {}
func (UnionString) ImplementsMeterCustomFieldsUnion()                           {}
func (UnionString) ImplementsMeterNewParamsCustomFieldsUnion()                  {}
func (UnionString) ImplementsMeterUpdateParamsCustomFieldsUnion()               {}
func (UnionString) ImplementsPlanCustomFieldsUnion()                            {}
func (UnionString) ImplementsPlanNewParamsCustomFieldsUnion()                   {}
func (UnionString) ImplementsPlanUpdateParamsCustomFieldsUnion()                {}
func (UnionString) ImplementsPlanGroupCustomFieldsUnion()                       {}
func (UnionString) ImplementsPlanGroupNewParamsCustomFieldsUnion()              {}
func (UnionString) ImplementsPlanGroupUpdateParamsCustomFieldsUnion()           {}
func (UnionString) ImplementsPlanTemplateCustomFieldsUnion()                    {}
func (UnionString) ImplementsPlanTemplateNewParamsCustomFieldsUnion()           {}
func (UnionString) ImplementsPlanTemplateUpdateParamsCustomFieldsUnion()        {}
func (UnionString) ImplementsProductCustomFieldsUnion()                         {}
func (UnionString) ImplementsProductNewParamsCustomFieldsUnion()                {}
func (UnionString) ImplementsProductUpdateParamsCustomFieldsUnion()             {}

type UnionFloat float64

func (UnionFloat) ImplementsAccountCustomFieldsUnion()                         {}
func (UnionFloat) ImplementsAccountNewParamsCustomFieldsUnion()                {}
func (UnionFloat) ImplementsAccountUpdateParamsCustomFieldsUnion()             {}
func (UnionFloat) ImplementsAccountPlanCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsAccountPlanNewParamsCustomFieldsUnion()            {}
func (UnionFloat) ImplementsAccountPlanUpdateParamsCustomFieldsUnion()         {}
func (UnionFloat) ImplementsAggregationCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsAggregationNewParamsCustomFieldsUnion()            {}
func (UnionFloat) ImplementsAggregationUpdateParamsCustomFieldsUnion()         {}
func (UnionFloat) ImplementsCompoundAggregationCustomFieldsUnion()             {}
func (UnionFloat) ImplementsCompoundAggregationNewParamsCustomFieldsUnion()    {}
func (UnionFloat) ImplementsCompoundAggregationUpdateParamsCustomFieldsUnion() {}
func (UnionFloat) ImplementsContractCustomFieldsUnion()                        {}
func (UnionFloat) ImplementsContractNewParamsCustomFieldsUnion()               {}
func (UnionFloat) ImplementsContractUpdateParamsCustomFieldsUnion()            {}
func (UnionFloat) ImplementsCustomFieldsAccountUnion()                         {}
func (UnionFloat) ImplementsCustomFieldsAccountPlanUnion()                     {}
func (UnionFloat) ImplementsCustomFieldsAggregationUnion()                     {}
func (UnionFloat) ImplementsCustomFieldsCompoundAggregationUnion()             {}
func (UnionFloat) ImplementsCustomFieldsMeterUnion()                           {}
func (UnionFloat) ImplementsCustomFieldsOrganizationUnion()                    {}
func (UnionFloat) ImplementsCustomFieldsPlanUnion()                            {}
func (UnionFloat) ImplementsCustomFieldsPlanTemplateUnion()                    {}
func (UnionFloat) ImplementsCustomFieldsProductUnion()                         {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsAccountUnion()              {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsAccountPlanUnion()          {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsAggregationUnion()          {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsCompoundAggregationUnion()  {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsMeterUnion()                {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsOrganizationUnion()         {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsPlanUnion()                 {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsPlanTemplateUnion()         {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsProductUnion()              {}
func (UnionFloat) ImplementsMeterCustomFieldsUnion()                           {}
func (UnionFloat) ImplementsMeterNewParamsCustomFieldsUnion()                  {}
func (UnionFloat) ImplementsMeterUpdateParamsCustomFieldsUnion()               {}
func (UnionFloat) ImplementsPlanCustomFieldsUnion()                            {}
func (UnionFloat) ImplementsPlanNewParamsCustomFieldsUnion()                   {}
func (UnionFloat) ImplementsPlanUpdateParamsCustomFieldsUnion()                {}
func (UnionFloat) ImplementsPlanGroupCustomFieldsUnion()                       {}
func (UnionFloat) ImplementsPlanGroupNewParamsCustomFieldsUnion()              {}
func (UnionFloat) ImplementsPlanGroupUpdateParamsCustomFieldsUnion()           {}
func (UnionFloat) ImplementsPlanTemplateCustomFieldsUnion()                    {}
func (UnionFloat) ImplementsPlanTemplateNewParamsCustomFieldsUnion()           {}
func (UnionFloat) ImplementsPlanTemplateUpdateParamsCustomFieldsUnion()        {}
func (UnionFloat) ImplementsProductCustomFieldsUnion()                         {}
func (UnionFloat) ImplementsProductNewParamsCustomFieldsUnion()                {}
func (UnionFloat) ImplementsProductUpdateParamsCustomFieldsUnion()             {}
