// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package shared

type UnionString string

func (UnionString) ImplementsAccountResponseCustomFieldsUnion()                      {}
func (UnionString) ImplementsAccountNewParamsCustomFieldsUnion()                     {}
func (UnionString) ImplementsAccountUpdateParamsCustomFieldsUnion()                  {}
func (UnionString) ImplementsAccountPlanResponseCustomFieldsUnion()                  {}
func (UnionString) ImplementsAccountPlanNewParamsCustomFieldsUnion()                 {}
func (UnionString) ImplementsAccountPlanUpdateParamsCustomFieldsUnion()              {}
func (UnionString) ImplementsAggregationResponseCustomFieldsUnion()                  {}
func (UnionString) ImplementsAggregationNewParamsCustomFieldsUnion()                 {}
func (UnionString) ImplementsAggregationUpdateParamsCustomFieldsUnion()              {}
func (UnionString) ImplementsBalanceCustomFieldsUnion()                              {}
func (UnionString) ImplementsBalanceNewParamsCustomFieldsUnion()                     {}
func (UnionString) ImplementsBalanceUpdateParamsCustomFieldsUnion()                  {}
func (UnionString) ImplementsScheduleRequestCustomFieldsUnionParam()                 {}
func (UnionString) ImplementsScheduleResponseCustomFieldsUnion()                     {}
func (UnionString) ImplementsBalanceChargeScheduleNewResponseCustomFieldsUnion()     {}
func (UnionString) ImplementsBalanceChargeScheduleGetResponseCustomFieldsUnion()     {}
func (UnionString) ImplementsBalanceChargeScheduleUpdateResponseCustomFieldsUnion()  {}
func (UnionString) ImplementsBalanceChargeScheduleListResponseCustomFieldsUnion()    {}
func (UnionString) ImplementsBalanceChargeScheduleDeleteResponseCustomFieldsUnion()  {}
func (UnionString) ImplementsBalanceChargeSchedulePreviewResponseCustomFieldsUnion() {}
func (UnionString) ImplementsBalanceChargeScheduleNewParamsCustomFieldsUnion()       {}
func (UnionString) ImplementsBalanceChargeScheduleUpdateParamsCustomFieldsUnion()    {}
func (UnionString) ImplementsBalanceChargeSchedulePreviewParamsCustomFieldsUnion()   {}
func (UnionString) ImplementsCompoundAggregationResponseCustomFieldsUnion()          {}
func (UnionString) ImplementsCompoundAggregationNewParamsCustomFieldsUnion()         {}
func (UnionString) ImplementsCompoundAggregationUpdateParamsCustomFieldsUnion()      {}
func (UnionString) ImplementsContractResponseCustomFieldsUnion()                     {}
func (UnionString) ImplementsContractNewParamsCustomFieldsUnion()                    {}
func (UnionString) ImplementsContractUpdateParamsCustomFieldsUnion()                 {}
func (UnionString) ImplementsCustomFieldsResponseAccountUnion()                      {}
func (UnionString) ImplementsCustomFieldsResponseAccountPlanUnion()                  {}
func (UnionString) ImplementsCustomFieldsResponseAggregationUnion()                  {}
func (UnionString) ImplementsCustomFieldsResponseCompoundAggregationUnion()          {}
func (UnionString) ImplementsCustomFieldsResponseContractUnion()                     {}
func (UnionString) ImplementsCustomFieldsResponseMeterUnion()                        {}
func (UnionString) ImplementsCustomFieldsResponseOrganizationUnion()                 {}
func (UnionString) ImplementsCustomFieldsResponsePlanUnion()                         {}
func (UnionString) ImplementsCustomFieldsResponsePlanTemplateUnion()                 {}
func (UnionString) ImplementsCustomFieldsResponseProductUnion()                      {}
func (UnionString) ImplementsCustomFieldUpdateParamsAccountUnion()                   {}
func (UnionString) ImplementsCustomFieldUpdateParamsAccountPlanUnion()               {}
func (UnionString) ImplementsCustomFieldUpdateParamsAggregationUnion()               {}
func (UnionString) ImplementsCustomFieldUpdateParamsCompoundAggregationUnion()       {}
func (UnionString) ImplementsCustomFieldUpdateParamsContractUnion()                  {}
func (UnionString) ImplementsCustomFieldUpdateParamsMeterUnion()                     {}
func (UnionString) ImplementsCustomFieldUpdateParamsOrganizationUnion()              {}
func (UnionString) ImplementsCustomFieldUpdateParamsPlanUnion()                      {}
func (UnionString) ImplementsCustomFieldUpdateParamsPlanTemplateUnion()              {}
func (UnionString) ImplementsCustomFieldUpdateParamsProductUnion()                   {}
func (UnionString) ImplementsLookupTableRequestCustomFieldsUnionParam()              {}
func (UnionString) ImplementsLookupTableResponseCustomFieldsUnion()                  {}
func (UnionString) ImplementsLookupTableRevisionRequestCustomFieldsUnionParam()      {}
func (UnionString) ImplementsLookupTableRevisionResponseCustomFieldsUnion()          {}
func (UnionString) ImplementsMeterResponseCustomFieldsUnion()                        {}
func (UnionString) ImplementsMeterNewParamsCustomFieldsUnion()                       {}
func (UnionString) ImplementsMeterUpdateParamsCustomFieldsUnion()                    {}
func (UnionString) ImplementsPlanResponseCustomFieldsUnion()                         {}
func (UnionString) ImplementsPlanNewParamsCustomFieldsUnion()                        {}
func (UnionString) ImplementsPlanUpdateParamsCustomFieldsUnion()                     {}
func (UnionString) ImplementsPlanGroupResponseCustomFieldsUnion()                    {}
func (UnionString) ImplementsPlanGroupNewParamsCustomFieldsUnion()                   {}
func (UnionString) ImplementsPlanGroupUpdateParamsCustomFieldsUnion()                {}
func (UnionString) ImplementsPlanTemplateResponseCustomFieldsUnion()                 {}
func (UnionString) ImplementsPlanTemplateNewParamsCustomFieldsUnion()                {}
func (UnionString) ImplementsPlanTemplateUpdateParamsCustomFieldsUnion()             {}
func (UnionString) ImplementsProductResponseCustomFieldsUnion()                      {}
func (UnionString) ImplementsProductNewParamsCustomFieldsUnion()                     {}
func (UnionString) ImplementsProductUpdateParamsCustomFieldsUnion()                  {}

type UnionFloat float64

func (UnionFloat) ImplementsAccountResponseCustomFieldsUnion()                      {}
func (UnionFloat) ImplementsAccountNewParamsCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsAccountUpdateParamsCustomFieldsUnion()                  {}
func (UnionFloat) ImplementsAccountPlanResponseCustomFieldsUnion()                  {}
func (UnionFloat) ImplementsAccountPlanNewParamsCustomFieldsUnion()                 {}
func (UnionFloat) ImplementsAccountPlanUpdateParamsCustomFieldsUnion()              {}
func (UnionFloat) ImplementsAggregationResponseCustomFieldsUnion()                  {}
func (UnionFloat) ImplementsAggregationNewParamsCustomFieldsUnion()                 {}
func (UnionFloat) ImplementsAggregationUpdateParamsCustomFieldsUnion()              {}
func (UnionFloat) ImplementsBalanceCustomFieldsUnion()                              {}
func (UnionFloat) ImplementsBalanceNewParamsCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsBalanceUpdateParamsCustomFieldsUnion()                  {}
func (UnionFloat) ImplementsScheduleRequestCustomFieldsUnionParam()                 {}
func (UnionFloat) ImplementsScheduleResponseCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsBalanceChargeScheduleNewResponseCustomFieldsUnion()     {}
func (UnionFloat) ImplementsBalanceChargeScheduleGetResponseCustomFieldsUnion()     {}
func (UnionFloat) ImplementsBalanceChargeScheduleUpdateResponseCustomFieldsUnion()  {}
func (UnionFloat) ImplementsBalanceChargeScheduleListResponseCustomFieldsUnion()    {}
func (UnionFloat) ImplementsBalanceChargeScheduleDeleteResponseCustomFieldsUnion()  {}
func (UnionFloat) ImplementsBalanceChargeSchedulePreviewResponseCustomFieldsUnion() {}
func (UnionFloat) ImplementsBalanceChargeScheduleNewParamsCustomFieldsUnion()       {}
func (UnionFloat) ImplementsBalanceChargeScheduleUpdateParamsCustomFieldsUnion()    {}
func (UnionFloat) ImplementsBalanceChargeSchedulePreviewParamsCustomFieldsUnion()   {}
func (UnionFloat) ImplementsCompoundAggregationResponseCustomFieldsUnion()          {}
func (UnionFloat) ImplementsCompoundAggregationNewParamsCustomFieldsUnion()         {}
func (UnionFloat) ImplementsCompoundAggregationUpdateParamsCustomFieldsUnion()      {}
func (UnionFloat) ImplementsContractResponseCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsContractNewParamsCustomFieldsUnion()                    {}
func (UnionFloat) ImplementsContractUpdateParamsCustomFieldsUnion()                 {}
func (UnionFloat) ImplementsCustomFieldsResponseAccountUnion()                      {}
func (UnionFloat) ImplementsCustomFieldsResponseAccountPlanUnion()                  {}
func (UnionFloat) ImplementsCustomFieldsResponseAggregationUnion()                  {}
func (UnionFloat) ImplementsCustomFieldsResponseCompoundAggregationUnion()          {}
func (UnionFloat) ImplementsCustomFieldsResponseContractUnion()                     {}
func (UnionFloat) ImplementsCustomFieldsResponseMeterUnion()                        {}
func (UnionFloat) ImplementsCustomFieldsResponseOrganizationUnion()                 {}
func (UnionFloat) ImplementsCustomFieldsResponsePlanUnion()                         {}
func (UnionFloat) ImplementsCustomFieldsResponsePlanTemplateUnion()                 {}
func (UnionFloat) ImplementsCustomFieldsResponseProductUnion()                      {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsAccountUnion()                   {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsAccountPlanUnion()               {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsAggregationUnion()               {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsCompoundAggregationUnion()       {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsContractUnion()                  {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsMeterUnion()                     {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsOrganizationUnion()              {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsPlanUnion()                      {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsPlanTemplateUnion()              {}
func (UnionFloat) ImplementsCustomFieldUpdateParamsProductUnion()                   {}
func (UnionFloat) ImplementsLookupTableRequestCustomFieldsUnionParam()              {}
func (UnionFloat) ImplementsLookupTableResponseCustomFieldsUnion()                  {}
func (UnionFloat) ImplementsLookupTableRevisionRequestCustomFieldsUnionParam()      {}
func (UnionFloat) ImplementsLookupTableRevisionResponseCustomFieldsUnion()          {}
func (UnionFloat) ImplementsMeterResponseCustomFieldsUnion()                        {}
func (UnionFloat) ImplementsMeterNewParamsCustomFieldsUnion()                       {}
func (UnionFloat) ImplementsMeterUpdateParamsCustomFieldsUnion()                    {}
func (UnionFloat) ImplementsPlanResponseCustomFieldsUnion()                         {}
func (UnionFloat) ImplementsPlanNewParamsCustomFieldsUnion()                        {}
func (UnionFloat) ImplementsPlanUpdateParamsCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsPlanGroupResponseCustomFieldsUnion()                    {}
func (UnionFloat) ImplementsPlanGroupNewParamsCustomFieldsUnion()                   {}
func (UnionFloat) ImplementsPlanGroupUpdateParamsCustomFieldsUnion()                {}
func (UnionFloat) ImplementsPlanTemplateResponseCustomFieldsUnion()                 {}
func (UnionFloat) ImplementsPlanTemplateNewParamsCustomFieldsUnion()                {}
func (UnionFloat) ImplementsPlanTemplateUpdateParamsCustomFieldsUnion()             {}
func (UnionFloat) ImplementsProductResponseCustomFieldsUnion()                      {}
func (UnionFloat) ImplementsProductNewParamsCustomFieldsUnion()                     {}
func (UnionFloat) ImplementsProductUpdateParamsCustomFieldsUnion()                  {}
